---
title: "R1"
author: "Swikar Adhikari"
date: "2024-11-10"
output: pdf_document
---

```{r}
n1 <- 15  
n1
typeof(n1)

n2 <- 1.5
n2
typeof(n2)
c1 <- "c"
c1
typeof(c1)

c2 <- "a string of text"
c2
typeof(c2)

# Logical
l1 <- TRUE
l1
typeof(l1)

l2 <- F
l2
typeof(l2)
num <- 10
numToChar <- as.character(num)
paste("num Type: ", typeof(num), " | numToChar: ", typeof(numToChar))

char <- "10"
charToNum <- as.numeric(char)
paste("char Type: ", typeof(char), " | charToNum: ", typeof(charToNum))
a <- as.integer(500)
b <- as.double(500)
c <- as.character(500)
typeof(a)
typeof(b)
typeof(c)
d <- a / b
typeof(d)
```
\newpage
```{r}

v1 <- c(1, 2, 3, 4, 5)
v1
is.vector(v1)

v2 <- c("a", "b", "c")
v2
is.vector(v2)

v3 <- c(TRUE, TRUE, FALSE, FALSE, TRUE)
v3
is.vector(v3)
m1 <- matrix(c(T, T, F, F, T, F), nrow = 2)
m1
is.matrix(m1)

m2 <- matrix(c("a", "b", "c", "d"), nrow = 2, byrow = TRUE)
m2
is.matrix(m2)
lowercase_letters <- letters
lowercase_letters

uppercase_matrix <- matrix(LETTERS, nrow = 2, byrow = TRUE)
uppercase_matrix
vNumeric <- c(1, 2, 3)
vCharacter <- c("a", "b", "c")
vLogical <- c(T, F, T)

df1 <- cbind(vNumeric, vCharacter, vLogical)
df1

df2 <- as.data.frame(cbind(vNumeric, vCharacter, vLogical))
df2
```
\newpage 
```{r, include=FALSE}

library(dplyr)
library(ggplot2)

packageVersion("dplyr")
ls("package:ggplot2")
ggplot2::geom_line
detach(package:ggplot2, unload=TRUE)
help(dplyr)
sessionInfo()
```
\newpage

```{r}
wd1 <- getwd()
paste("Current Working Directory: ", wd1)
library(ggplot2)
# Part a
x <- 4

# Part b
y <- 12

# Part c
print(x)
print(y)

# Part d
z <- y / x

# Part e
print(paste("y divided by x is equal to ", z))

if (exists("x") == TRUE | exists("y") == TRUE | exists("z") == TRUE){
  if (x == 4 & y == 12 & z == 3) {
    print("Congratulation!!  You completed the first activity in this class!!")
  } else {
    print("Sorry, you got it wrong!")
  }
} else {
  print("You did not complete the last problem!")
}
```
